import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { loadAllPosts } from '../lib/api'
import type Post from '../interfaces/post'

type Props = {
  posts: Array<Post>
}

const Home: NextPage<Props> = ({ posts }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section>
        <h1>Recent Posts:</h1>
        <ul>
        {posts.map((post) => (
          <li key={post.slug}>
            <span>{post.date}</span>
            {' '}
            <Link href={`/posts/${post.slug}`} passHref>
              <a>{post.title}</a>
            </Link>
          </li>
        ))}
        </ul>
        </section>
      </main>
      <footer className={styles.footer}>
        Simmons I/O &copy; {new Date().getFullYear()}
      </footer>
    </div>
  )
}

export default Home

export async function getStaticProps() {
  return {
    props: { posts: loadAllPosts(), }
  }
}
